name: Publish

on:
  push:
    branches:
      - 'master'
    
env:
  CACHE_VERSION: v1

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: package-version-to-git-tag
      #   uses: pkgdeps/action-package-version-to-git-tag@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     github_repo: ${{ github.repository }}
      #     git_commit_sha: ${{ github.sha }}
      #     git_tag_prefix: "v"
      # GitHub Packages への公開のために.npmrcファイルをセットアップ
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12'
      # # GitHub Packagesへの公開
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   # npmへの公開のために.npmrcファイルをセットアップ
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12'
      # - run: npm install
      # # npmへの公開
      # - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      # - run: cat ~/.npmrc
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # GitHub Packages への公開のために.npmrcファイルをセットアップ
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12'
      # # GitHub Packagesへの公開
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}