name: Publish

on:
  push:
    branches:
      - 'master'
    
env:
  CACHE_VERSION: v1

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # - name: Cache dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-
      # - name: update package version
      # - run: npm version patch
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install can-npm-publish and dependencies
        run: |
          npm install can-npm-publish
          npm ci
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ｜
          npx can-npm-publish
          if [ $? -eq 1 ] ; then
            exit 255
          fi

          # get current version from package.json
          TAG=$(cat package.json | grep version | cut -d " " -f 4 | tr -d "," | tr -d '"')
          echo "add new tag to GitHub: ${TAG}"

          # Add tag to GitHub
          API_URL="https://api.github.com/repos/${REPO}/git/refs"

          curl -s -X POST $API_URL \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d @- << EOS
          {
            "ref": "refs/tags/${TAG}",
            "sha": "${COMMIT}"
          }
          EOS
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shokorep'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}