name: Publish

on:
  push:
    branches:
      - 'master'
    
env:
  CACHE_VERSION: v1

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-
      - name: Login
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - name: publish
        run: npm publish --access=public